# Generated by Django 6.0.3 on 2026-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
    ]
